services:
  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

  discovery-server:
    build:
      context: ./Backend/discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      - TZ=Asia/Kolkata

  api-gateway:
    build:
      context: ./Backend/api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka/
      - TZ=Asia/Kolkata
    depends_on:
      - discovery-server

  auth-service:
    build:
      context: ./Backend/auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka/
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092
      - TZ=Asia/Kolkata
    depends_on:
      - discovery-server
      - broker

  wallet-service:
    build:
      context: ./Backend/wallet-service
    container_name: wallet-service
    ports:
      - "8082:8082"
    environment:
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka/
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092
      - TZ=Asia/Kolkata
    depends_on:
      - discovery-server
      - broker

  transaction-service:
    build:
      context: ./Backend/transaction-service
    container_name: transaction-service
    ports:
      - "8083:8083"
    environment:
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka/
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092
      - TZ=Asia/Kolkata
    depends_on:
      - discovery-server
      - broker

  rewards-service:
    build:
      context: ./Backend/rewards-service
    container_name: rewards-service
    ports:
      - "8084:8084"
    environment:
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka/
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092
      - TZ=Asia/Kolkata
    depends_on:
      - discovery-server
      - broker

  notification-service:
    build:
      context: ./Backend/notification-service
    container_name: notification-service
    ports:
      - "8085:8085"
    environment:
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka/
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092
      - TZ=Asia/Kolkata
    depends_on:
      - discovery-server
      - broker

  frontend:
    build:
      context: ./Frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - api-gateway
